# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: careerbuilder.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='careerbuilder.proto',
  package='cb',
  serialized_pb='\n\x13\x63\x61reerbuilder.proto\x12\x02\x63\x62\"\x87\x01\n\x03Job\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05title\x18\x02 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\tother_ids\x18\x04 \x03(\x05\x42\x02\x10\x01\"2\n\x04Type\x12\r\n\tFULL_TIME\x10\x00\x12\r\n\tPART_TIME\x10\x01\x12\x0c\n\x08\x43ONTRACT\x10\x02*\x05\x08\x64\x10\xb8\x17\"\x8a\x02\n\x07\x43ompany\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x15\n\x04jobs\x18\x03 \x03(\x0b\x32\x07.cb.Job\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x13\n\x07ranking\x18\x05 \x01(\x05:\x02\x31\x30\x12&\n\x05phone\x18\x06 \x03(\x0b\x32\x17.cb.Company.PhoneNumber\x1aH\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x02(\t\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x15.cb.Company.PhoneType:\x04HOME\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x03*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\x42\x02H\x02')



_JOB_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='cb.Job.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FULL_TIME', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PART_TIME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTRACT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=106,
  serialized_end=156,
)

_COMPANY_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='cb.Company.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=378,
  serialized_end=421,
)


_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='cb.Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cb.Job.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='cb.Job.title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='cb.Job.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='other_ids', full_name='cb.Job.other_ids', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOB_TYPE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 3000), ],
  serialized_start=28,
  serialized_end=163,
)


_COMPANY_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='cb.Company.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='cb.Company.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='cb.Company.PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=304,
  serialized_end=376,
)

_COMPANY = _descriptor.Descriptor(
  name='Company',
  full_name='cb.Company',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cb.Company.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='cb.Company.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jobs', full_name='cb.Company.jobs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='cb.Company.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ranking', full_name='cb.Company.ranking', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='cb.Company.phone', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_COMPANY_PHONENUMBER, ],
  enum_types=[
    _COMPANY_PHONETYPE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1000, 536870912), ],
  serialized_start=166,
  serialized_end=432,
)

_JOB_TYPE.containing_type = _JOB;
_COMPANY_PHONENUMBER.fields_by_name['type'].enum_type = _COMPANY_PHONETYPE
_COMPANY_PHONENUMBER.containing_type = _COMPANY;
_COMPANY.fields_by_name['jobs'].message_type = _JOB
_COMPANY.fields_by_name['phone'].message_type = _COMPANY_PHONENUMBER
_COMPANY_PHONETYPE.containing_type = _COMPANY;
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['Company'] = _COMPANY

class Job(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOB

  # @@protoc_insertion_point(class_scope:cb.Job)

class Company(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class PhoneNumber(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _COMPANY_PHONENUMBER

    # @@protoc_insertion_point(class_scope:cb.Company.PhoneNumber)
  DESCRIPTOR = _COMPANY

  # @@protoc_insertion_point(class_scope:cb.Company)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\002')
_JOB.fields_by_name['other_ids'].has_options = True
_JOB.fields_by_name['other_ids']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
