// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: careerbuilder.proto

package cb;

public final class Careerbuilder {
  private Careerbuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JobOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Job> {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     *The number is a Tag between 1 to 2^29 - use to encode param in bin
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     *The number is a Tag between 1 to 2^29 - use to encode param in bin
     * </pre>
     */
    int getId();

    // required string title = 2;
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     *title will be required ForEver
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     *title will be required ForEver
     * </pre>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     *title will be required ForEver
     * </pre>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // optional string description = 3;
    /**
     * <code>optional string description = 3;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // repeated int32 other_ids = 4 [packed = true];
    /**
     * <code>repeated int32 other_ids = 4 [packed = true];</code>
     *
     * <pre>
     *optimize version for encoding arrays of numbers
     * </pre>
     */
    java.util.List<java.lang.Integer> getOtherIdsList();
    /**
     * <code>repeated int32 other_ids = 4 [packed = true];</code>
     *
     * <pre>
     *optimize version for encoding arrays of numbers
     * </pre>
     */
    int getOtherIdsCount();
    /**
     * <code>repeated int32 other_ids = 4 [packed = true];</code>
     *
     * <pre>
     *optimize version for encoding arrays of numbers
     * </pre>
     */
    int getOtherIds(int index);
  }
  /**
   * Protobuf type {@code cb.Job}
   */
  public static final class Job extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Job> implements JobOrBuilder {
    // Use Job.newBuilder() to construct.
    private Job(com.google.protobuf.GeneratedMessage.ExtendableBuilder<cb.Careerbuilder.Job, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Job(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Job defaultInstance;
    public static Job getDefaultInstance() {
      return defaultInstance;
    }

    public Job getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cb.Careerbuilder.internal_static_cb_Job_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cb.Careerbuilder.internal_static_cb_Job_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cb.Careerbuilder.Job.class, cb.Careerbuilder.Job.Builder.class);
    }

    public static com.google.protobuf.Parser<Job> PARSER =
        new com.google.protobuf.AbstractParser<Job>() {
      public Job parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Job> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code cb.Job.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FULL_TIME = 0;</code>
       */
      FULL_TIME(0, 0),
      /**
       * <code>PART_TIME = 1;</code>
       */
      PART_TIME(1, 1),
      /**
       * <code>CONTRACT = 2;</code>
       */
      CONTRACT(2, 2),
      ;

      /**
       * <code>FULL_TIME = 0;</code>
       */
      public static final int FULL_TIME_VALUE = 0;
      /**
       * <code>PART_TIME = 1;</code>
       */
      public static final int PART_TIME_VALUE = 1;
      /**
       * <code>CONTRACT = 2;</code>
       */
      public static final int CONTRACT_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return FULL_TIME;
          case 1: return PART_TIME;
          case 2: return CONTRACT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cb.Careerbuilder.Job.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cb.Job.Type)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     *The number is a Tag between 1 to 2^29 - use to encode param in bin
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     *The number is a Tag between 1 to 2^29 - use to encode param in bin
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     *title will be required ForEver
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     *title will be required ForEver
     * </pre>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 2;</code>
     *
     * <pre>
     *title will be required ForEver
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 3;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated int32 other_ids = 4 [packed = true];
    public static final int OTHER_IDS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> otherIds_;
    /**
     * <code>repeated int32 other_ids = 4 [packed = true];</code>
     *
     * <pre>
     *optimize version for encoding arrays of numbers
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getOtherIdsList() {
      return otherIds_;
    }
    /**
     * <code>repeated int32 other_ids = 4 [packed = true];</code>
     *
     * <pre>
     *optimize version for encoding arrays of numbers
     * </pre>
     */
    public int getOtherIdsCount() {
      return otherIds_.size();
    }
    /**
     * <code>repeated int32 other_ids = 4 [packed = true];</code>
     *
     * <pre>
     *optimize version for encoding arrays of numbers
     * </pre>
     */
    public int getOtherIds(int index) {
      return otherIds_.get(index);
    }

    private void initFields() {
      id_ = 0;
      title_ = "";
      description_ = "";
      otherIds_ = java.util.Collections.emptyList();
    }
    public static cb.Careerbuilder.Job parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cb.Careerbuilder.Job parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cb.Careerbuilder.Job parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cb.Careerbuilder.Job parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cb.Careerbuilder.Job parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cb.Careerbuilder.Job parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cb.Careerbuilder.Job parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cb.Careerbuilder.Job parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cb.Careerbuilder.Job parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cb.Careerbuilder.Job parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cb.Careerbuilder.Job prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cb.Job}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          cb.Careerbuilder.Job, Builder> implements cb.Careerbuilder.JobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cb.Careerbuilder.internal_static_cb_Job_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cb.Careerbuilder.internal_static_cb_Job_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cb.Careerbuilder.Job.class, cb.Careerbuilder.Job.Builder.class);
      }

      // Construct using cb.Careerbuilder.Job.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        otherIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cb.Careerbuilder.internal_static_cb_Job_descriptor;
      }

      public cb.Careerbuilder.Job getDefaultInstanceForType() {
        return cb.Careerbuilder.Job.getDefaultInstance();
      }

      public cb.Careerbuilder.Job build() {
        cb.Careerbuilder.Job result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cb.Careerbuilder.Job buildPartial() {
        cb.Careerbuilder.Job result = new cb.Careerbuilder.Job(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          otherIds_ = java.util.Collections.unmodifiableList(otherIds_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.otherIds_ = otherIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       *The number is a Tag between 1 to 2^29 - use to encode param in bin
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       *The number is a Tag between 1 to 2^29 - use to encode param in bin
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       *The number is a Tag between 1 to 2^29 - use to encode param in bin
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       *The number is a Tag between 1 to 2^29 - use to encode param in bin
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string title = 2;
      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       *title will be required ForEver
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       *title will be required ForEver
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       *title will be required ForEver
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       *title will be required ForEver
       * </pre>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       *title will be required ForEver
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       *
       * <pre>
       *title will be required ForEver
       * </pre>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      // optional string description = 3;
      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 3;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }

      // repeated int32 other_ids = 4 [packed = true];
      private java.util.List<java.lang.Integer> otherIds_ = java.util.Collections.emptyList();
      private void ensureOtherIdsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          otherIds_ = new java.util.ArrayList<java.lang.Integer>(otherIds_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 other_ids = 4 [packed = true];</code>
       *
       * <pre>
       *optimize version for encoding arrays of numbers
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getOtherIdsList() {
        return java.util.Collections.unmodifiableList(otherIds_);
      }
      /**
       * <code>repeated int32 other_ids = 4 [packed = true];</code>
       *
       * <pre>
       *optimize version for encoding arrays of numbers
       * </pre>
       */
      public int getOtherIdsCount() {
        return otherIds_.size();
      }
      /**
       * <code>repeated int32 other_ids = 4 [packed = true];</code>
       *
       * <pre>
       *optimize version for encoding arrays of numbers
       * </pre>
       */
      public int getOtherIds(int index) {
        return otherIds_.get(index);
      }
      /**
       * <code>repeated int32 other_ids = 4 [packed = true];</code>
       *
       * <pre>
       *optimize version for encoding arrays of numbers
       * </pre>
       */
      public Builder setOtherIds(
          int index, int value) {
        ensureOtherIdsIsMutable();
        otherIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 other_ids = 4 [packed = true];</code>
       *
       * <pre>
       *optimize version for encoding arrays of numbers
       * </pre>
       */
      public Builder addOtherIds(int value) {
        ensureOtherIdsIsMutable();
        otherIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 other_ids = 4 [packed = true];</code>
       *
       * <pre>
       *optimize version for encoding arrays of numbers
       * </pre>
       */
      public Builder addAllOtherIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureOtherIdsIsMutable();
        super.addAll(values, otherIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 other_ids = 4 [packed = true];</code>
       *
       * <pre>
       *optimize version for encoding arrays of numbers
       * </pre>
       */
      public Builder clearOtherIds() {
        otherIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cb.Job)
    }

    static {
      defaultInstance = new Job(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cb.Job)
  }

  public interface CompanyOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Company> {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .cb.Job jobs = 3;
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    java.util.List<cb.Careerbuilder.Job> 
        getJobsList();
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    cb.Careerbuilder.Job getJobs(int index);
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    int getJobsCount();
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    java.util.List<? extends cb.Careerbuilder.JobOrBuilder> 
        getJobsOrBuilderList();
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    cb.Careerbuilder.JobOrBuilder getJobsOrBuilder(
        int index);

    // optional string address = 4;
    /**
     * <code>optional string address = 4;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 4;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    // optional int32 ranking = 5 [default = 10];
    /**
     * <code>optional int32 ranking = 5 [default = 10];</code>
     */
    boolean hasRanking();
    /**
     * <code>optional int32 ranking = 5 [default = 10];</code>
     */
    int getRanking();

    // repeated .cb.Company.PhoneNumber phone = 6;
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    java.util.List<cb.Careerbuilder.Company.PhoneNumber> 
        getPhoneList();
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    cb.Careerbuilder.Company.PhoneNumber getPhone(int index);
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    int getPhoneCount();
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    java.util.List<? extends cb.Careerbuilder.Company.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList();
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    cb.Careerbuilder.Company.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cb.Company}
   */
  public static final class Company extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Company> implements CompanyOrBuilder {
    // Use Company.newBuilder() to construct.
    private Company(com.google.protobuf.GeneratedMessage.ExtendableBuilder<cb.Careerbuilder.Company, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Company(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Company defaultInstance;
    public static Company getDefaultInstance() {
      return defaultInstance;
    }

    public Company getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cb.Careerbuilder.internal_static_cb_Company_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cb.Careerbuilder.internal_static_cb_Company_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cb.Careerbuilder.Company.class, cb.Careerbuilder.Company.Builder.class);
    }

    public static com.google.protobuf.Parser<Company> PARSER =
        new com.google.protobuf.AbstractParser<Company>() {
      public Company parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Company> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code cb.Company.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0, 0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1, 1),
      /**
       * <code>WORK = 3;</code>
       */
      WORK(2, 3),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 3;</code>
       */
      public static final int WORK_VALUE = 3;


      public final int getNumber() { return value; }

      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 3: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cb.Careerbuilder.Company.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cb.Company.PhoneType)
    }

    public interface PhoneNumberOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string number = 1;
      /**
       * <code>required string number = 1;</code>
       */
      boolean hasNumber();
      /**
       * <code>required string number = 1;</code>
       */
      java.lang.String getNumber();
      /**
       * <code>required string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      // optional .cb.Company.PhoneType type = 2 [default = HOME];
      /**
       * <code>optional .cb.Company.PhoneType type = 2 [default = HOME];</code>
       */
      boolean hasType();
      /**
       * <code>optional .cb.Company.PhoneType type = 2 [default = HOME];</code>
       */
      cb.Careerbuilder.Company.PhoneType getType();
    }
    /**
     * Protobuf type {@code cb.Company.PhoneNumber}
     */
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessage
        implements PhoneNumberOrBuilder {
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private PhoneNumber(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final PhoneNumber defaultInstance;
      public static PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }

      public PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cb.Careerbuilder.internal_static_cb_Company_PhoneNumber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cb.Careerbuilder.internal_static_cb_Company_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cb.Careerbuilder.Company.PhoneNumber.class, cb.Careerbuilder.Company.PhoneNumber.Builder.class);
      }

      public static com.google.protobuf.Parser<PhoneNumber> PARSER =
          new com.google.protobuf.AbstractParser<PhoneNumber>() {
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string number = 1;
      public static final int NUMBER_FIELD_NUMBER = 1;
      private java.lang.Object number_;
      /**
       * <code>required string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .cb.Company.PhoneType type = 2 [default = HOME];
      public static final int TYPE_FIELD_NUMBER = 2;
      private cb.Careerbuilder.Company.PhoneType type_;
      /**
       * <code>optional .cb.Company.PhoneType type = 2 [default = HOME];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .cb.Company.PhoneType type = 2 [default = HOME];</code>
       */
      public cb.Careerbuilder.Company.PhoneType getType() {
        return type_;
      }

      private void initFields() {
        number_ = "";
        type_ = cb.Careerbuilder.Company.PhoneType.HOME;
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static cb.Careerbuilder.Company.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(cb.Careerbuilder.Company.PhoneNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code cb.Company.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements cb.Careerbuilder.Company.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cb.Careerbuilder.internal_static_cb_Company_PhoneNumber_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cb.Careerbuilder.internal_static_cb_Company_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cb.Careerbuilder.Company.PhoneNumber.class, cb.Careerbuilder.Company.PhoneNumber.Builder.class);
        }

        // Construct using cb.Careerbuilder.Company.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          number_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = cb.Careerbuilder.Company.PhoneType.HOME;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cb.Careerbuilder.internal_static_cb_Company_PhoneNumber_descriptor;
        }

        public cb.Careerbuilder.Company.PhoneNumber getDefaultInstanceForType() {
          return cb.Careerbuilder.Company.PhoneNumber.getDefaultInstance();
        }

        public cb.Careerbuilder.Company.PhoneNumber build() {
          cb.Careerbuilder.Company.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public cb.Careerbuilder.Company.PhoneNumber buildPartial() {
          cb.Careerbuilder.Company.PhoneNumber result = new cb.Careerbuilder.Company.PhoneNumber(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.number_ = number_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        private int bitField0_;

        // required string number = 1;
        private java.lang.Object number_ = "";
        /**
         * <code>required string number = 1;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string number = 1;</code>
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }

        // optional .cb.Company.PhoneType type = 2 [default = HOME];
        private cb.Careerbuilder.Company.PhoneType type_ = cb.Careerbuilder.Company.PhoneType.HOME;
        /**
         * <code>optional .cb.Company.PhoneType type = 2 [default = HOME];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .cb.Company.PhoneType type = 2 [default = HOME];</code>
         */
        public cb.Careerbuilder.Company.PhoneType getType() {
          return type_;
        }
        /**
         * <code>optional .cb.Company.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder setType(cb.Careerbuilder.Company.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .cb.Company.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = cb.Careerbuilder.Company.PhoneType.HOME;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:cb.Company.PhoneNumber)
      }

      static {
        defaultInstance = new PhoneNumber(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:cb.Company.PhoneNumber)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .cb.Job jobs = 3;
    public static final int JOBS_FIELD_NUMBER = 3;
    private java.util.List<cb.Careerbuilder.Job> jobs_;
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    public java.util.List<cb.Careerbuilder.Job> getJobsList() {
      return jobs_;
    }
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    public java.util.List<? extends cb.Careerbuilder.JobOrBuilder> 
        getJobsOrBuilderList() {
      return jobs_;
    }
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    public int getJobsCount() {
      return jobs_.size();
    }
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    public cb.Careerbuilder.Job getJobs(int index) {
      return jobs_.get(index);
    }
    /**
     * <code>repeated .cb.Job jobs = 3;</code>
     */
    public cb.Careerbuilder.JobOrBuilder getJobsOrBuilder(
        int index) {
      return jobs_.get(index);
    }

    // optional string address = 4;
    public static final int ADDRESS_FIELD_NUMBER = 4;
    private java.lang.Object address_;
    /**
     * <code>optional string address = 4;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string address = 4;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 ranking = 5 [default = 10];
    public static final int RANKING_FIELD_NUMBER = 5;
    private int ranking_;
    /**
     * <code>optional int32 ranking = 5 [default = 10];</code>
     */
    public boolean hasRanking() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 ranking = 5 [default = 10];</code>
     */
    public int getRanking() {
      return ranking_;
    }

    // repeated .cb.Company.PhoneNumber phone = 6;
    public static final int PHONE_FIELD_NUMBER = 6;
    private java.util.List<cb.Careerbuilder.Company.PhoneNumber> phone_;
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    public java.util.List<cb.Careerbuilder.Company.PhoneNumber> getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    public java.util.List<? extends cb.Careerbuilder.Company.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    public cb.Careerbuilder.Company.PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
     */
    public cb.Careerbuilder.Company.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      jobs_ = java.util.Collections.emptyList();
      address_ = "";
      ranking_ = 10;
      phone_ = java.util.Collections.emptyList();
    }
    public static cb.Careerbuilder.Company parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cb.Careerbuilder.Company parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cb.Careerbuilder.Company parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cb.Careerbuilder.Company parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cb.Careerbuilder.Company parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cb.Careerbuilder.Company parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cb.Careerbuilder.Company parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cb.Careerbuilder.Company parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cb.Careerbuilder.Company parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cb.Careerbuilder.Company parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cb.Careerbuilder.Company prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cb.Company}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          cb.Careerbuilder.Company, Builder> implements cb.Careerbuilder.CompanyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cb.Careerbuilder.internal_static_cb_Company_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cb.Careerbuilder.internal_static_cb_Company_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cb.Careerbuilder.Company.class, cb.Careerbuilder.Company.Builder.class);
      }

      // Construct using cb.Careerbuilder.Company.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJobsFieldBuilder();
          getPhoneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (jobsBuilder_ == null) {
          jobs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          jobsBuilder_.clear();
        }
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        ranking_ = 10;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cb.Careerbuilder.internal_static_cb_Company_descriptor;
      }

      public cb.Careerbuilder.Company getDefaultInstanceForType() {
        return cb.Careerbuilder.Company.getDefaultInstance();
      }

      public cb.Careerbuilder.Company build() {
        cb.Careerbuilder.Company result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cb.Careerbuilder.Company buildPartial() {
        cb.Careerbuilder.Company result = new cb.Careerbuilder.Company(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (jobsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            jobs_ = java.util.Collections.unmodifiableList(jobs_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.jobs_ = jobs_;
        } else {
          result.jobs_ = jobsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ranking_ = ranking_;
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .cb.Job jobs = 3;
      private java.util.List<cb.Careerbuilder.Job> jobs_ =
        java.util.Collections.emptyList();
      private void ensureJobsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          jobs_ = new java.util.ArrayList<cb.Careerbuilder.Job>(jobs_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cb.Careerbuilder.Job, cb.Careerbuilder.Job.Builder, cb.Careerbuilder.JobOrBuilder> jobsBuilder_;

      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public java.util.List<cb.Careerbuilder.Job> getJobsList() {
        if (jobsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(jobs_);
        } else {
          return jobsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public int getJobsCount() {
        if (jobsBuilder_ == null) {
          return jobs_.size();
        } else {
          return jobsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public cb.Careerbuilder.Job getJobs(int index) {
        if (jobsBuilder_ == null) {
          return jobs_.get(index);
        } else {
          return jobsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder setJobs(
          int index, cb.Careerbuilder.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.set(index, value);
          onChanged();
        } else {
          jobsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder setJobs(
          int index, cb.Careerbuilder.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.set(index, builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder addJobs(cb.Careerbuilder.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.add(value);
          onChanged();
        } else {
          jobsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder addJobs(
          int index, cb.Careerbuilder.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.add(index, value);
          onChanged();
        } else {
          jobsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder addJobs(
          cb.Careerbuilder.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.add(builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder addJobs(
          int index, cb.Careerbuilder.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.add(index, builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder addAllJobs(
          java.lang.Iterable<? extends cb.Careerbuilder.Job> values) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          super.addAll(values, jobs_);
          onChanged();
        } else {
          jobsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder clearJobs() {
        if (jobsBuilder_ == null) {
          jobs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          jobsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public Builder removeJobs(int index) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.remove(index);
          onChanged();
        } else {
          jobsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public cb.Careerbuilder.Job.Builder getJobsBuilder(
          int index) {
        return getJobsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public cb.Careerbuilder.JobOrBuilder getJobsOrBuilder(
          int index) {
        if (jobsBuilder_ == null) {
          return jobs_.get(index);  } else {
          return jobsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public java.util.List<? extends cb.Careerbuilder.JobOrBuilder> 
           getJobsOrBuilderList() {
        if (jobsBuilder_ != null) {
          return jobsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(jobs_);
        }
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public cb.Careerbuilder.Job.Builder addJobsBuilder() {
        return getJobsFieldBuilder().addBuilder(
            cb.Careerbuilder.Job.getDefaultInstance());
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public cb.Careerbuilder.Job.Builder addJobsBuilder(
          int index) {
        return getJobsFieldBuilder().addBuilder(
            index, cb.Careerbuilder.Job.getDefaultInstance());
      }
      /**
       * <code>repeated .cb.Job jobs = 3;</code>
       */
      public java.util.List<cb.Careerbuilder.Job.Builder> 
           getJobsBuilderList() {
        return getJobsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cb.Careerbuilder.Job, cb.Careerbuilder.Job.Builder, cb.Careerbuilder.JobOrBuilder> 
          getJobsFieldBuilder() {
        if (jobsBuilder_ == null) {
          jobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cb.Careerbuilder.Job, cb.Careerbuilder.Job.Builder, cb.Careerbuilder.JobOrBuilder>(
                  jobs_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          jobs_ = null;
        }
        return jobsBuilder_;
      }

      // optional string address = 4;
      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 4;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 4;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }

      // optional int32 ranking = 5 [default = 10];
      private int ranking_ = 10;
      /**
       * <code>optional int32 ranking = 5 [default = 10];</code>
       */
      public boolean hasRanking() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 ranking = 5 [default = 10];</code>
       */
      public int getRanking() {
        return ranking_;
      }
      /**
       * <code>optional int32 ranking = 5 [default = 10];</code>
       */
      public Builder setRanking(int value) {
        bitField0_ |= 0x00000010;
        ranking_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ranking = 5 [default = 10];</code>
       */
      public Builder clearRanking() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ranking_ = 10;
        onChanged();
        return this;
      }

      // repeated .cb.Company.PhoneNumber phone = 6;
      private java.util.List<cb.Careerbuilder.Company.PhoneNumber> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          phone_ = new java.util.ArrayList<cb.Careerbuilder.Company.PhoneNumber>(phone_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cb.Careerbuilder.Company.PhoneNumber, cb.Careerbuilder.Company.PhoneNumber.Builder, cb.Careerbuilder.Company.PhoneNumberOrBuilder> phoneBuilder_;

      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public java.util.List<cb.Careerbuilder.Company.PhoneNumber> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public cb.Careerbuilder.Company.PhoneNumber getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder setPhone(
          int index, cb.Careerbuilder.Company.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder setPhone(
          int index, cb.Careerbuilder.Company.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder addPhone(cb.Careerbuilder.Company.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder addPhone(
          int index, cb.Careerbuilder.Company.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder addPhone(
          cb.Careerbuilder.Company.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder addPhone(
          int index, cb.Careerbuilder.Company.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<? extends cb.Careerbuilder.Company.PhoneNumber> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          super.addAll(values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public cb.Careerbuilder.Company.PhoneNumber.Builder getPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public cb.Careerbuilder.Company.PhoneNumberOrBuilder getPhoneOrBuilder(
          int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);  } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public java.util.List<? extends cb.Careerbuilder.Company.PhoneNumberOrBuilder> 
           getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public cb.Careerbuilder.Company.PhoneNumber.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
            cb.Careerbuilder.Company.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public cb.Careerbuilder.Company.PhoneNumber.Builder addPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().addBuilder(
            index, cb.Careerbuilder.Company.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .cb.Company.PhoneNumber phone = 6;</code>
       */
      public java.util.List<cb.Careerbuilder.Company.PhoneNumber.Builder> 
           getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cb.Careerbuilder.Company.PhoneNumber, cb.Careerbuilder.Company.PhoneNumber.Builder, cb.Careerbuilder.Company.PhoneNumberOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cb.Careerbuilder.Company.PhoneNumber, cb.Careerbuilder.Company.PhoneNumber.Builder, cb.Careerbuilder.Company.PhoneNumberOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cb.Company)
    }

    static {
      defaultInstance = new Company(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cb.Company)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cb_Job_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cb_Job_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cb_Company_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cb_Company_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cb_Company_PhoneNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cb_Company_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023careerbuilder.proto\022\002cb\"\207\001\n\003Job\022\n\n\002id\030" +
      "\001 \002(\005\022\r\n\005title\030\002 \002(\t\022\023\n\013description\030\003 \001(" +
      "\t\022\025\n\tother_ids\030\004 \003(\005B\002\020\001\"2\n\004Type\022\r\n\tFULL" +
      "_TIME\020\000\022\r\n\tPART_TIME\020\001\022\014\n\010CONTRACT\020\002*\005\010d" +
      "\020\270\027\"\212\002\n\007Company\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(" +
      "\t\022\025\n\004jobs\030\003 \003(\0132\007.cb.Job\022\017\n\007address\030\004 \001(" +
      "\t\022\023\n\007ranking\030\005 \001(\005:\00210\022&\n\005phone\030\006 \003(\0132\027." +
      "cb.Company.PhoneNumber\032H\n\013PhoneNumber\022\016\n" +
      "\006number\030\001 \002(\t\022)\n\004type\030\002 \001(\0162\025.cb.Company" +
      ".PhoneType:\004HOME\"+\n\tPhoneType\022\n\n\006MOBILE\020",
      "\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\003*\t\010\350\007\020\200\200\200\200\002B\002H\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cb_Job_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cb_Job_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cb_Job_descriptor,
              new java.lang.String[] { "Id", "Title", "Description", "OtherIds", });
          internal_static_cb_Company_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cb_Company_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cb_Company_descriptor,
              new java.lang.String[] { "Id", "Name", "Jobs", "Address", "Ranking", "Phone", });
          internal_static_cb_Company_PhoneNumber_descriptor =
            internal_static_cb_Company_descriptor.getNestedTypes().get(0);
          internal_static_cb_Company_PhoneNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cb_Company_PhoneNumber_descriptor,
              new java.lang.String[] { "Number", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
